# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b971d5aa56f3b7e346824ab9fd1c6c8240b2dda29c8ee7c389cee0fe489969a92814caf57e1f60c3fa2d2bfbe558e62dc00dd4ed7bcba79a6097925de1939987

test:
  secret_key_base: fd707fc2b53c39a57654b03a2ed536ff9dd3ced6af2efc6951fab43829c6fbaf97f8f1a17c40acdc7cf520baa7f2eb1afe13a47a660d7169b6f37f6b82c7b2c4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
